;; -*- coding: utf-8 -*-
(setq-default c-basic-offset 4)
(defun wttr/cc-mode:basic-setup ()
  "Set setting for cc mode"
  (highlight-indentation-current-column-mode)
  (highlight-indentation-mode)
  (yas-minor-mode)
  (auto-complete-mode)
  (c-set-style "stroustrup")
  (idle-highlight-mode)
  (rtags-start-process-unless-running)
  (local-set-key (kbd "M-g M-g") 'rtags-find-symbol-at-point)
  (local-set-key (kbd "M-g o") 'rtags-show-target-in-other-window)
  (local-set-key (kbd "M-g f") 'rtags-location-stack-forward)
  (local-set-key (kbd "M-g b") 'rtags-location-stack-back)
  (local-set-key (kbd "M-g r") 'rtags-find-references-at-point)
  )
;; (c-toggle-auto-hungry-state))
;;(modify-syntax-entry ?_ "w" c++-mode-syntax-table)
(add-hook 'c-mode-common-hook 'wttr/cc-mode:basic-setup)
(add-to-list 'auto-mode-alist '("\\.h\\'" . c++-mode))
(add-to-list 'auto-mode-alist '("\\.mm\\'" . objc-mode))
