;;(setq load-path (cons (expand-file-name "/opt/emacs_plugins") load-path))  
(require 'cmake-mode)
(setq auto-mode-alist  
      (append '(("CMakeLists\\.txt\\'" . cmake-mode)  
                ("\\.cmake\\'" . cmake-mode))  
              auto-mode-alist))
(defun cmake-hook()
  (company-mode)
  (yas-minor-mode)
  (set (make-local-variable 'company-backends)
       '((company-dabbrev-code company-yasnippet  company-abbrev company-cmake)))
  )
(add-hook 'cmake-mode-hook 'elisp-hook)
