(require 'yasnippet)
(require 'lsp-bridge)
(defun my-c-mode-hook()
  (yas-global-mode 1)
  (lsp-bridge-mode)
  (setq acm-enable-codeium 1)
  (local-set-key (kbd "M-q") 'kill-current-buffer)
  (local-set-key (kbd "<f12>") 'lsp-bridge-find-def)
  (local-set-key (kbd "C-<f12>") 'lsp-bridge-peek)
  (local-set-key (kbd "C-c r") 'lsp-bridge-rename)
  (local-set-key (kbd "S-<f12>") 'lsp-bridge-find-references)
  (local-set-key (kbd "M-<return>") 'lsp-bridge-code-action)
  (local-set-key (kbd "C-\\") 'lsp-bridge-code-format)
  (local-set-key (kbd "M-<left>") 'lsp-bridge-find-def-return)
  (local-set-key (kbd "<f5>") 'realgud:gdb)
  (local-set-key (kbd "<mouse-8>") 'lsp-bridge-find-def-return)
  )
(add-hook 'c++-mode-hook 'my-c-mode-hook)

(require 'flymake-bridge)
(add-hook 'lsp-bridge-mode-hook #'flymake-bridge-setup)
